/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AGMSettings {
  'venue' : string,
  'sessionTimeoutMinutes' : bigint,
  'quorumThreshold' : bigint,
  'agmDate' : string,
  'agmName' : string,
}
export interface AppUser {
  'principal' : string,
  'username' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'isActive' : boolean,
  'passwordHash' : string,
  'sessionExpiry' : [] | [bigint],
  'lastLogin' : [] | [bigint],
  'mustChangePassword' : boolean,
}
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'entityId' : string,
  'performedAt' : bigint,
  'performedBy' : string,
  'details' : string,
  'entityType' : string,
  'ipAddress' : [] | [string],
}
export interface BulkCreateResult {
  'created' : bigint,
  'errors' : Array<string>,
  'duplicates' : bigint,
}
export interface CheckIn {
  'id' : string,
  'shareholderId' : string,
  'method' : CheckInMethod,
  'checkedInAt' : bigint,
  'checkedInBy' : string,
  'registrationId' : string,
}
export type CheckInMethod = { 'ManualQuick' : null } |
  { 'QRScan' : null } |
  { 'Manual' : null };
export interface DashboardMetrics {
  'totalShareholders' : bigint,
  'quorumStatus' : boolean,
  'lastUpdated' : bigint,
  'registeredInPerson' : bigint,
  'attendanceRate' : number,
  'registeredProxy' : bigint,
  'checkedIn' : bigint,
  'notRegistered' : bigint,
  'registered' : bigint,
}
export interface ImportBatch {
  'id' : string,
  'status' : ImportStatus,
  'totalRows' : bigint,
  'duplicatesSkipped' : bigint,
  'filename' : string,
  'importedRows' : bigint,
  'uploadedAt' : bigint,
  'uploadedBy' : string,
}
export type ImportStatus = { 'Failed' : null } |
  { 'Complete' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export interface LoginResponse {
  'token' : string,
  'username' : string,
  'role' : UserRole,
  'mustChangePassword' : boolean,
}
export interface ProxyData {
  'proxyContact' : string,
  'proxyProofKey' : [] | [string],
  'proxyName' : string,
}
export interface Registration {
  'id' : string,
  'shareholderId' : string,
  'verificationCode' : string,
  'proxyContact' : [] | [string],
  'proxyProofKey' : [] | [string],
  'updatedAt' : bigint,
  'updatedBy' : [] | [string],
  'proxyFraudFlags' : Array<string>,
  'notes' : [] | [string],
  'proxyName' : [] | [string],
  'proxyProofValidated' : boolean,
  'registrationType' : RegistrationType,
  'registeredAt' : bigint,
  'registeredBy' : string,
}
export type RegistrationType = { 'Proxy' : null } |
  { 'InPerson' : null };
export interface RegistrationUpdate {
  'proxyData' : [] | [ProxyData],
  'notes' : [] | [string],
}
export interface SearchResult {
  'total' : bigint,
  'page' : bigint,
  'items' : Array<Shareholder>,
}
export interface Session {
  'token' : string,
  'expiresAt' : bigint,
  'username' : string,
  'role' : UserRole,
}
export interface Shareholder {
  'id' : string,
  'status' : ShareholderStatus,
  'tags' : Array<string>,
  'fullName' : string,
  'importedAt' : bigint,
  'importedBy' : string,
  'email' : [] | [string],
  'shareholderNumber' : string,
  'idNumber' : string,
  'phone' : [] | [string],
  'shareholding' : bigint,
}
export interface ShareholderInput {
  'tags' : Array<string>,
  'fullName' : string,
  'email' : [] | [string],
  'shareholderNumber' : string,
  'idNumber' : string,
  'phone' : [] | [string],
  'shareholding' : bigint,
}
export type ShareholderStatus = { 'RegisteredProxy' : null } |
  { 'RegisteredInPerson' : null } |
  { 'NotRegistered' : null } |
  { 'CheckedIn' : null };
export type UserRole = { 'Viewer' : null } |
  { 'RegistrationOfficer' : null } |
  { 'SuperAdmin' : null };
export interface _SERVICE {
  'bulkCreateShareholders' : ActorMethod<
    [Array<ShareholderInput>, string],
    BulkCreateResult
  >,
  'cancelRegistration' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'checkInShareholder' : ActorMethod<
    [string, string, CheckInMethod, string],
    { 'ok' : CheckIn } |
      { 'err' : string }
  >,
  'createImportBatch' : ActorMethod<[string, string, bigint], ImportBatch>,
  'createShareholder' : ActorMethod<
    [ShareholderInput, string],
    { 'ok' : Shareholder } |
      { 'err' : string }
  >,
  'createUser' : ActorMethod<
    [string, string, string, UserRole],
    { 'ok' : AppUser } |
      { 'err' : string }
  >,
  'deactivateUser' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteAllShareholders' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'forceLogout' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActiveSessions' : ActorMethod<
    [string],
    { 'ok' : Array<Session> } |
      { 'err' : string }
  >,
  'getAllCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getAllShareholders' : ActorMethod<[], Array<Shareholder>>,
  'getAuditLog' : ActorMethod<
    [[] | [string], [] | [string], bigint],
    Array<AuditEntry>
  >,
  'getAuditLogForExport' : ActorMethod<[], Array<AuditEntry>>,
  'getCheckIn' : ActorMethod<[string], [] | [CheckIn]>,
  'getCheckInByShareholder' : ActorMethod<[string], [] | [CheckIn]>,
  'getDashboardMetrics' : ActorMethod<[bigint], DashboardMetrics>,
  'getImportBatch' : ActorMethod<[string], [] | [ImportBatch]>,
  'getImportBatches' : ActorMethod<[], Array<ImportBatch>>,
  'getRegistration' : ActorMethod<[string], [] | [Registration]>,
  'getRegistrationByShareholder' : ActorMethod<[string], [] | [Registration]>,
  'getSettings' : ActorMethod<[], AGMSettings>,
  'getShareholder' : ActorMethod<[string], [] | [Shareholder]>,
  'getShareholderByNumber' : ActorMethod<[string], [] | [Shareholder]>,
  'getUsers' : ActorMethod<
    [string],
    { 'ok' : Array<AppUser> } |
      { 'err' : string }
  >,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : LoginResponse } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'registerShareholder' : ActorMethod<
    [string, RegistrationType, [] | [ProxyData], string],
    { 'ok' : Registration } |
      { 'err' : string }
  >,
  'resetPasswordWithCode' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchShareholders' : ActorMethod<
    [string, [] | [ShareholderStatus], bigint, bigint],
    SearchResult
  >,
  'undoCheckIn' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateImportBatchStatus' : ActorMethod<
    [string, ImportStatus, bigint, bigint],
    { 'ok' : ImportBatch } |
      { 'err' : string }
  >,
  'updateRegistration' : ActorMethod<
    [string, RegistrationUpdate, string],
    { 'ok' : Registration } |
      { 'err' : string }
  >,
  'updateSettings' : ActorMethod<
    [string, AGMSettings],
    { 'ok' : AGMSettings } |
      { 'err' : string }
  >,
  'updateShareholderStatus' : ActorMethod<
    [string, ShareholderStatus, string],
    { 'ok' : Shareholder } |
      { 'err' : string }
  >,
  'updateUserRole' : ActorMethod<
    [string, string, UserRole],
    { 'ok' : AppUser } |
      { 'err' : string }
  >,
  'validateProxyProof' : ActorMethod<
    [string, boolean, Array<string>, string],
    { 'ok' : Registration } |
      { 'err' : string }
  >,
  'validateSession' : ActorMethod<
    [string],
    { 'ok' : Session } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];