/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShareholderInput = IDL.Record({
  'tags' : IDL.Vec(IDL.Text),
  'fullName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'shareholderNumber' : IDL.Text,
  'idNumber' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'shareholding' : IDL.Nat,
});
export const BulkCreateResult = IDL.Record({
  'created' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
  'duplicates' : IDL.Nat,
});
export const CheckInMethod = IDL.Variant({
  'ManualQuick' : IDL.Null,
  'QRScan' : IDL.Null,
  'Manual' : IDL.Null,
});
export const CheckIn = IDL.Record({
  'id' : IDL.Text,
  'shareholderId' : IDL.Text,
  'method' : CheckInMethod,
  'checkedInAt' : IDL.Int,
  'checkedInBy' : IDL.Text,
  'registrationId' : IDL.Text,
});
export const ImportStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Complete' : IDL.Null,
  'Processing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ImportBatch = IDL.Record({
  'id' : IDL.Text,
  'status' : ImportStatus,
  'totalRows' : IDL.Nat,
  'duplicatesSkipped' : IDL.Nat,
  'filename' : IDL.Text,
  'importedRows' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Text,
});
export const ShareholderStatus = IDL.Variant({
  'RegisteredProxy' : IDL.Null,
  'RegisteredInPerson' : IDL.Null,
  'NotRegistered' : IDL.Null,
  'CheckedIn' : IDL.Null,
});
export const Shareholder = IDL.Record({
  'id' : IDL.Text,
  'status' : ShareholderStatus,
  'tags' : IDL.Vec(IDL.Text),
  'fullName' : IDL.Text,
  'importedAt' : IDL.Int,
  'importedBy' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'shareholderNumber' : IDL.Text,
  'idNumber' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'shareholding' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'Viewer' : IDL.Null,
  'RegistrationOfficer' : IDL.Null,
  'SuperAdmin' : IDL.Null,
});
export const AppUser = IDL.Record({
  'principal' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'sessionExpiry' : IDL.Opt(IDL.Int),
  'lastLogin' : IDL.Opt(IDL.Int),
  'mustChangePassword' : IDL.Bool,
});
export const Session = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const RegistrationType = IDL.Variant({
  'Proxy' : IDL.Null,
  'InPerson' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : IDL.Text,
  'shareholderId' : IDL.Text,
  'verificationCode' : IDL.Text,
  'proxyContact' : IDL.Opt(IDL.Text),
  'proxyProofKey' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'updatedBy' : IDL.Opt(IDL.Text),
  'proxyFraudFlags' : IDL.Vec(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'proxyName' : IDL.Opt(IDL.Text),
  'proxyProofValidated' : IDL.Bool,
  'registrationType' : RegistrationType,
  'registeredAt' : IDL.Int,
  'registeredBy' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'performedAt' : IDL.Int,
  'performedBy' : IDL.Text,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
  'ipAddress' : IDL.Opt(IDL.Text),
});
export const DashboardMetrics = IDL.Record({
  'totalShareholders' : IDL.Nat,
  'quorumStatus' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'registeredInPerson' : IDL.Nat,
  'attendanceRate' : IDL.Float64,
  'registeredProxy' : IDL.Nat,
  'checkedIn' : IDL.Nat,
  'notRegistered' : IDL.Nat,
  'registered' : IDL.Nat,
});
export const AGMSettings = IDL.Record({
  'venue' : IDL.Text,
  'sessionTimeoutMinutes' : IDL.Nat,
  'quorumThreshold' : IDL.Nat,
  'agmDate' : IDL.Text,
  'agmName' : IDL.Text,
});
export const LoginResponse = IDL.Record({
  'token' : IDL.Text,
  'username' : IDL.Text,
  'role' : UserRole,
  'mustChangePassword' : IDL.Bool,
});
export const ProxyData = IDL.Record({
  'proxyContact' : IDL.Text,
  'proxyProofKey' : IDL.Opt(IDL.Text),
  'proxyName' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'items' : IDL.Vec(Shareholder),
});
export const RegistrationUpdate = IDL.Record({
  'proxyData' : IDL.Opt(ProxyData),
  'notes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'bulkCreateShareholders' : IDL.Func(
      [IDL.Vec(ShareholderInput), IDL.Text],
      [BulkCreateResult],
      [],
    ),
  'cancelRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'checkInShareholder' : IDL.Func(
      [IDL.Text, IDL.Text, CheckInMethod, IDL.Text],
      [IDL.Variant({ 'ok' : CheckIn, 'err' : IDL.Text })],
      [],
    ),
  'createImportBatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [ImportBatch],
      [],
    ),
  'createShareholder' : IDL.Func(
      [ShareholderInput, IDL.Text],
      [IDL.Variant({ 'ok' : Shareholder, 'err' : IDL.Text })],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : AppUser, 'err' : IDL.Text })],
      [],
    ),
  'deactivateUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteAllShareholders' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'forceLogout' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Session), 'err' : IDL.Text })],
      [],
    ),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getAllShareholders' : IDL.Func([], [IDL.Vec(Shareholder)], ['query']),
  'getAuditLog' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'getAuditLogForExport' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'getCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(CheckIn)], ['query']),
  'getCheckInByShareholder' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CheckIn)],
      ['query'],
    ),
  'getDashboardMetrics' : IDL.Func([IDL.Nat], [DashboardMetrics], ['query']),
  'getImportBatch' : IDL.Func([IDL.Text], [IDL.Opt(ImportBatch)], ['query']),
  'getImportBatches' : IDL.Func([], [IDL.Vec(ImportBatch)], ['query']),
  'getRegistration' : IDL.Func([IDL.Text], [IDL.Opt(Registration)], ['query']),
  'getRegistrationByShareholder' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Registration)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AGMSettings], ['query']),
  'getShareholder' : IDL.Func([IDL.Text], [IDL.Opt(Shareholder)], ['query']),
  'getShareholderByNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Shareholder)],
      ['query'],
    ),
  'getUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AppUser), 'err' : IDL.Text })],
      [],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : LoginResponse, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'registerShareholder' : IDL.Func(
      [IDL.Text, RegistrationType, IDL.Opt(ProxyData), IDL.Text],
      [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
      [],
    ),
  'resetPasswordWithCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchShareholders' : IDL.Func(
      [IDL.Text, IDL.Opt(ShareholderStatus), IDL.Nat, IDL.Nat],
      [SearchResult],
      ['query'],
    ),
  'undoCheckIn' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateImportBatchStatus' : IDL.Func(
      [IDL.Text, ImportStatus, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : ImportBatch, 'err' : IDL.Text })],
      [],
    ),
  'updateRegistration' : IDL.Func(
      [IDL.Text, RegistrationUpdate, IDL.Text],
      [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
      [],
    ),
  'updateSettings' : IDL.Func(
      [IDL.Text, AGMSettings],
      [IDL.Variant({ 'ok' : AGMSettings, 'err' : IDL.Text })],
      [],
    ),
  'updateShareholderStatus' : IDL.Func(
      [IDL.Text, ShareholderStatus, IDL.Text],
      [IDL.Variant({ 'ok' : Shareholder, 'err' : IDL.Text })],
      [],
    ),
  'updateUserRole' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : AppUser, 'err' : IDL.Text })],
      [],
    ),
  'validateProxyProof' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
      [],
    ),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : Session, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShareholderInput = IDL.Record({
    'tags' : IDL.Vec(IDL.Text),
    'fullName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'shareholderNumber' : IDL.Text,
    'idNumber' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'shareholding' : IDL.Nat,
  });
  const BulkCreateResult = IDL.Record({
    'created' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
    'duplicates' : IDL.Nat,
  });
  const CheckInMethod = IDL.Variant({
    'ManualQuick' : IDL.Null,
    'QRScan' : IDL.Null,
    'Manual' : IDL.Null,
  });
  const CheckIn = IDL.Record({
    'id' : IDL.Text,
    'shareholderId' : IDL.Text,
    'method' : CheckInMethod,
    'checkedInAt' : IDL.Int,
    'checkedInBy' : IDL.Text,
    'registrationId' : IDL.Text,
  });
  const ImportStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Complete' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ImportBatch = IDL.Record({
    'id' : IDL.Text,
    'status' : ImportStatus,
    'totalRows' : IDL.Nat,
    'duplicatesSkipped' : IDL.Nat,
    'filename' : IDL.Text,
    'importedRows' : IDL.Nat,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Text,
  });
  const ShareholderStatus = IDL.Variant({
    'RegisteredProxy' : IDL.Null,
    'RegisteredInPerson' : IDL.Null,
    'NotRegistered' : IDL.Null,
    'CheckedIn' : IDL.Null,
  });
  const Shareholder = IDL.Record({
    'id' : IDL.Text,
    'status' : ShareholderStatus,
    'tags' : IDL.Vec(IDL.Text),
    'fullName' : IDL.Text,
    'importedAt' : IDL.Int,
    'importedBy' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'shareholderNumber' : IDL.Text,
    'idNumber' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'shareholding' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'Viewer' : IDL.Null,
    'RegistrationOfficer' : IDL.Null,
    'SuperAdmin' : IDL.Null,
  });
  const AppUser = IDL.Record({
    'principal' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'sessionExpiry' : IDL.Opt(IDL.Int),
    'lastLogin' : IDL.Opt(IDL.Int),
    'mustChangePassword' : IDL.Bool,
  });
  const Session = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const RegistrationType = IDL.Variant({
    'Proxy' : IDL.Null,
    'InPerson' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : IDL.Text,
    'shareholderId' : IDL.Text,
    'verificationCode' : IDL.Text,
    'proxyContact' : IDL.Opt(IDL.Text),
    'proxyProofKey' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'updatedBy' : IDL.Opt(IDL.Text),
    'proxyFraudFlags' : IDL.Vec(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'proxyName' : IDL.Opt(IDL.Text),
    'proxyProofValidated' : IDL.Bool,
    'registrationType' : RegistrationType,
    'registeredAt' : IDL.Int,
    'registeredBy' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'performedAt' : IDL.Int,
    'performedBy' : IDL.Text,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
    'ipAddress' : IDL.Opt(IDL.Text),
  });
  const DashboardMetrics = IDL.Record({
    'totalShareholders' : IDL.Nat,
    'quorumStatus' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'registeredInPerson' : IDL.Nat,
    'attendanceRate' : IDL.Float64,
    'registeredProxy' : IDL.Nat,
    'checkedIn' : IDL.Nat,
    'notRegistered' : IDL.Nat,
    'registered' : IDL.Nat,
  });
  const AGMSettings = IDL.Record({
    'venue' : IDL.Text,
    'sessionTimeoutMinutes' : IDL.Nat,
    'quorumThreshold' : IDL.Nat,
    'agmDate' : IDL.Text,
    'agmName' : IDL.Text,
  });
  const LoginResponse = IDL.Record({
    'token' : IDL.Text,
    'username' : IDL.Text,
    'role' : UserRole,
    'mustChangePassword' : IDL.Bool,
  });
  const ProxyData = IDL.Record({
    'proxyContact' : IDL.Text,
    'proxyProofKey' : IDL.Opt(IDL.Text),
    'proxyName' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'items' : IDL.Vec(Shareholder),
  });
  const RegistrationUpdate = IDL.Record({
    'proxyData' : IDL.Opt(ProxyData),
    'notes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'bulkCreateShareholders' : IDL.Func(
        [IDL.Vec(ShareholderInput), IDL.Text],
        [BulkCreateResult],
        [],
      ),
    'cancelRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'checkInShareholder' : IDL.Func(
        [IDL.Text, IDL.Text, CheckInMethod, IDL.Text],
        [IDL.Variant({ 'ok' : CheckIn, 'err' : IDL.Text })],
        [],
      ),
    'createImportBatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [ImportBatch],
        [],
      ),
    'createShareholder' : IDL.Func(
        [ShareholderInput, IDL.Text],
        [IDL.Variant({ 'ok' : Shareholder, 'err' : IDL.Text })],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : AppUser, 'err' : IDL.Text })],
        [],
      ),
    'deactivateUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteAllShareholders' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'forceLogout' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Session), 'err' : IDL.Text })],
        [],
      ),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getAllShareholders' : IDL.Func([], [IDL.Vec(Shareholder)], ['query']),
    'getAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'getAuditLogForExport' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'getCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(CheckIn)], ['query']),
    'getCheckInByShareholder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CheckIn)],
        ['query'],
      ),
    'getDashboardMetrics' : IDL.Func([IDL.Nat], [DashboardMetrics], ['query']),
    'getImportBatch' : IDL.Func([IDL.Text], [IDL.Opt(ImportBatch)], ['query']),
    'getImportBatches' : IDL.Func([], [IDL.Vec(ImportBatch)], ['query']),
    'getRegistration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getRegistrationByShareholder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AGMSettings], ['query']),
    'getShareholder' : IDL.Func([IDL.Text], [IDL.Opt(Shareholder)], ['query']),
    'getShareholderByNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Shareholder)],
        ['query'],
      ),
    'getUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AppUser), 'err' : IDL.Text })],
        [],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : LoginResponse, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'registerShareholder' : IDL.Func(
        [IDL.Text, RegistrationType, IDL.Opt(ProxyData), IDL.Text],
        [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
        [],
      ),
    'resetPasswordWithCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchShareholders' : IDL.Func(
        [IDL.Text, IDL.Opt(ShareholderStatus), IDL.Nat, IDL.Nat],
        [SearchResult],
        ['query'],
      ),
    'undoCheckIn' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateImportBatchStatus' : IDL.Func(
        [IDL.Text, ImportStatus, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : ImportBatch, 'err' : IDL.Text })],
        [],
      ),
    'updateRegistration' : IDL.Func(
        [IDL.Text, RegistrationUpdate, IDL.Text],
        [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
        [],
      ),
    'updateSettings' : IDL.Func(
        [IDL.Text, AGMSettings],
        [IDL.Variant({ 'ok' : AGMSettings, 'err' : IDL.Text })],
        [],
      ),
    'updateShareholderStatus' : IDL.Func(
        [IDL.Text, ShareholderStatus, IDL.Text],
        [IDL.Variant({ 'ok' : Shareholder, 'err' : IDL.Text })],
        [],
      ),
    'updateUserRole' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : AppUser, 'err' : IDL.Text })],
        [],
      ),
    'validateProxyProof' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Variant({ 'ok' : Registration, 'err' : IDL.Text })],
        [],
      ),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : Session, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };