/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchResult {
    total: bigint;
    page: bigint;
    items: Array<Shareholder>;
}
export interface Shareholder {
    id: string;
    status: ShareholderStatus;
    tags: Array<string>;
    fullName: string;
    importedAt: bigint;
    importedBy: string;
    email?: string;
    shareholderNumber: string;
    idNumber: string;
    phone?: string;
    shareholding: bigint;
}
export interface RegistrationUpdate {
    proxyData?: ProxyData;
    notes?: string;
}
export interface ShareholderInput {
    tags: Array<string>;
    fullName: string;
    email?: string;
    shareholderNumber: string;
    idNumber: string;
    phone?: string;
    shareholding: bigint;
}
export interface ImportBatch {
    id: string;
    status: ImportStatus;
    totalRows: bigint;
    duplicatesSkipped: bigint;
    filename: string;
    importedRows: bigint;
    uploadedAt: bigint;
    uploadedBy: string;
}
export interface Registration {
    id: string;
    shareholderId: string;
    verificationCode: string;
    proxyContact?: string;
    proxyProofKey?: string;
    updatedAt: bigint;
    updatedBy?: string;
    proxyFraudFlags: Array<string>;
    notes?: string;
    proxyName?: string;
    proxyProofValidated: boolean;
    registrationType: RegistrationType;
    registeredAt: bigint;
    registeredBy: string;
}
export interface ProxyData {
    proxyContact: string;
    proxyProofKey?: string;
    proxyName: string;
}
export interface BulkCreateResult {
    created: bigint;
    errors: Array<string>;
    duplicates: bigint;
}
export interface CheckIn {
    id: string;
    shareholderId: string;
    method: CheckInMethod;
    checkedInAt: bigint;
    checkedInBy: string;
    registrationId: string;
}
export interface Session {
    token: string;
    expiresAt: bigint;
    username: string;
    role: UserRole;
}
export interface AuditEntry {
    id: string;
    action: string;
    entityId: string;
    performedAt: bigint;
    performedBy: string;
    details: string;
    entityType: string;
    ipAddress?: string;
}
export interface AppUser {
    principal: string;
    username: string;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    passwordHash: string;
    sessionExpiry?: bigint;
    lastLogin?: bigint;
    mustChangePassword: boolean;
}
export interface AGMSettings {
    venue: string;
    sessionTimeoutMinutes: bigint;
    quorumThreshold: bigint;
    agmDate: string;
    agmName: string;
}
export interface DashboardMetrics {
    totalShareholders: bigint;
    quorumStatus: boolean;
    lastUpdated: bigint;
    registeredInPerson: bigint;
    attendanceRate: number;
    registeredProxy: bigint;
    checkedIn: bigint;
    notRegistered: bigint;
    registered: bigint;
}
export interface LoginResponse {
    token: string;
    username: string;
    role: UserRole;
    mustChangePassword: boolean;
}
export enum CheckInMethod {
    ManualQuick = "ManualQuick",
    QRScan = "QRScan",
    Manual = "Manual"
}
export enum ImportStatus {
    Failed = "Failed",
    Complete = "Complete",
    Processing = "Processing",
    Pending = "Pending"
}
export enum RegistrationType {
    Proxy = "Proxy",
    InPerson = "InPerson"
}
export enum ShareholderStatus {
    RegisteredProxy = "RegisteredProxy",
    RegisteredInPerson = "RegisteredInPerson",
    NotRegistered = "NotRegistered",
    CheckedIn = "CheckedIn"
}
export enum UserRole {
    Viewer = "Viewer",
    RegistrationOfficer = "RegistrationOfficer",
    SuperAdmin = "SuperAdmin"
}
export interface backendInterface {
    bulkCreateShareholders(items: Array<ShareholderInput>, importedBy: string): Promise<BulkCreateResult>;
    cancelRegistration(id: string, cancelledBy: string, reason: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changePassword(username: string, oldPassword: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    checkInShareholder(shareholderId: string, registrationId: string, method: CheckInMethod, checkedInBy: string): Promise<{
        __kind__: "ok";
        ok: CheckIn;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createImportBatch(filename: string, uploadedBy: string, totalRows: bigint): Promise<ImportBatch>;
    createShareholder(data: ShareholderInput, importedBy: string): Promise<{
        __kind__: "ok";
        ok: Shareholder;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createUser(adminToken: string, username: string, password: string, role: UserRole): Promise<{
        __kind__: "ok";
        ok: AppUser;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deactivateUser(adminToken: string, username: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteAllShareholders(deletedBy: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    forceLogout(adminToken: string, username: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActiveSessions(adminToken: string): Promise<{
        __kind__: "ok";
        ok: Array<Session>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllCheckIns(): Promise<Array<CheckIn>>;
    getAllRegistrations(): Promise<Array<Registration>>;
    getAllShareholders(): Promise<Array<Shareholder>>;
    getAuditLog(entityType: string | null, entityId: string | null, limit: bigint): Promise<Array<AuditEntry>>;
    getAuditLogForExport(): Promise<Array<AuditEntry>>;
    getCheckIn(id: string): Promise<CheckIn | null>;
    getCheckInByShareholder(shareholderId: string): Promise<CheckIn | null>;
    getDashboardMetrics(quorumThreshold: bigint): Promise<DashboardMetrics>;
    getImportBatch(id: string): Promise<ImportBatch | null>;
    getImportBatches(): Promise<Array<ImportBatch>>;
    getRegistration(id: string): Promise<Registration | null>;
    getRegistrationByShareholder(shareholderId: string): Promise<Registration | null>;
    getSettings(): Promise<AGMSettings>;
    getShareholder(id: string): Promise<Shareholder | null>;
    getShareholderByNumber(shareholderNumber: string): Promise<Shareholder | null>;
    getUsers(adminToken: string): Promise<{
        __kind__: "ok";
        ok: Array<AppUser>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    login(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: LoginResponse;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logout(token: string): Promise<void>;
    registerShareholder(shareholderId: string, regType: RegistrationType, proxyData: ProxyData | null, registeredBy: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetPasswordWithCode(username: string, resetCode: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchShareholders(searchQuery: string, statusFilter: ShareholderStatus | null, page: bigint, pageSize: bigint): Promise<SearchResult>;
    undoCheckIn(shareholderId: string, undoneBy: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateImportBatchStatus(id: string, status: ImportStatus, importedRows: bigint, duplicates: bigint): Promise<{
        __kind__: "ok";
        ok: ImportBatch;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateRegistration(id: string, updates: RegistrationUpdate, updatedBy: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSettings(adminToken: string, newSettings: AGMSettings): Promise<{
        __kind__: "ok";
        ok: AGMSettings;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateShareholderStatus(id: string, status: ShareholderStatus, updatedBy: string): Promise<{
        __kind__: "ok";
        ok: Shareholder;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserRole(adminToken: string, username: string, role: UserRole): Promise<{
        __kind__: "ok";
        ok: AppUser;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateProxyProof(registrationId: string, validated: boolean, fraudFlags: Array<string>, validatedBy: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }>;
    validateSession(token: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AGMSettings as _AGMSettings, AppUser as _AppUser, AuditEntry as _AuditEntry, CheckIn as _CheckIn, CheckInMethod as _CheckInMethod, ImportBatch as _ImportBatch, ImportStatus as _ImportStatus, LoginResponse as _LoginResponse, ProxyData as _ProxyData, Registration as _Registration, RegistrationType as _RegistrationType, RegistrationUpdate as _RegistrationUpdate, SearchResult as _SearchResult, Session as _Session, Shareholder as _Shareholder, ShareholderInput as _ShareholderInput, ShareholderStatus as _ShareholderStatus, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bulkCreateShareholders(arg0: Array<ShareholderInput>, arg1: string): Promise<BulkCreateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkCreateShareholders(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkCreateShareholders(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async cancelRegistration(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRegistration(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRegistration(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async changePassword(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changePassword(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePassword(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkInShareholder(arg0: string, arg1: string, arg2: CheckInMethod, arg3: string): Promise<{
        __kind__: "ok";
        ok: CheckIn;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInShareholder(arg0, arg1, to_candid_CheckInMethod_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInShareholder(arg0, arg1, to_candid_CheckInMethod_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createImportBatch(arg0: string, arg1: string, arg2: bigint): Promise<ImportBatch> {
        if (this.processError) {
            try {
                const result = await this.actor.createImportBatch(arg0, arg1, arg2);
                return from_candid_ImportBatch_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImportBatch(arg0, arg1, arg2);
            return from_candid_ImportBatch_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShareholder(arg0: ShareholderInput, arg1: string): Promise<{
        __kind__: "ok";
        ok: Shareholder;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createShareholder(to_candid_ShareholderInput_n2(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShareholder(to_candid_ShareholderInput_n2(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: UserRole): Promise<{
        __kind__: "ok";
        ok: AppUser;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAllShareholders(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllShareholders(arg0);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllShareholders(arg0);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async forceLogout(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.forceLogout(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceLogout(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveSessions(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<Session>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSessions(arg0);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSessions(arg0);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCheckIns(): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCheckIns();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCheckIns();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrations();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrations();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShareholders(): Promise<Array<Shareholder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShareholders();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShareholders();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: string | null, arg1: string | null, arg2: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(to_candid_opt_n42(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(to_candid_opt_n42(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogForExport(): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogForExport();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogForExport();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckIn(arg0: string): Promise<CheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckIn(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckIn(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInByShareholder(arg0: string): Promise<CheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInByShareholder(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInByShareholder(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(arg0: bigint): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics(arg0);
            return result;
        }
    }
    async getImportBatch(arg0: string): Promise<ImportBatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportBatch(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportBatch(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImportBatches(): Promise<Array<ImportBatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportBatches();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportBatches();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistration(arg0: string): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistration(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistration(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationByShareholder(arg0: string): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationByShareholder(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationByShareholder(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AGMSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getShareholder(arg0: string): Promise<Shareholder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareholder(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareholder(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShareholderByNumber(arg0: string): Promise<Shareholder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareholderByNumber(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareholderByNumber(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<AppUser>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: LoginResponse;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async registerShareholder(arg0: string, arg1: RegistrationType, arg2: ProxyData | null, arg3: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerShareholder(arg0, to_candid_RegistrationType_n56(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerShareholder(arg0, to_candid_RegistrationType_n56(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPasswordWithCode(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithCode(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithCode(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchShareholders(arg0: string, arg1: ShareholderStatus | null, arg2: bigint, arg3: bigint): Promise<SearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchShareholders(arg0, to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_SearchResult_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchShareholders(arg0, to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_SearchResult_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async undoCheckIn(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.undoCheckIn(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.undoCheckIn(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateImportBatchStatus(arg0: string, arg1: ImportStatus, arg2: bigint, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: ImportBatch;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImportBatchStatus(arg0, to_candid_ImportStatus_n67(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImportBatchStatus(arg0, to_candid_ImportStatus_n67(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_variant_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRegistration(arg0: string, arg1: RegistrationUpdate, arg2: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistration(arg0, to_candid_RegistrationUpdate_n70(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistration(arg0, to_candid_RegistrationUpdate_n70(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: string, arg1: AGMSettings): Promise<{
        __kind__: "ok";
        ok: AGMSettings;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0, arg1);
                return from_candid_variant_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0, arg1);
            return from_candid_variant_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateShareholderStatus(arg0: string, arg1: ShareholderStatus, arg2: string): Promise<{
        __kind__: "ok";
        ok: Shareholder;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShareholderStatus(arg0, to_candid_ShareholderStatus_n63(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShareholderStatus(arg0, to_candid_ShareholderStatus_n63(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: string, arg1: string, arg2: UserRole): Promise<{
        __kind__: "ok";
        ok: AppUser;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, arg1, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, arg1, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateProxyProof(arg0: string, arg1: boolean, arg2: Array<string>, arg3: string): Promise<{
        __kind__: "ok";
        ok: Registration;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateProxyProof(arg0, arg1, arg2, arg3);
                return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateProxyProof(arg0, arg1, arg2, arg3);
            return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: Session;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_variant_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_variant_n73(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppUser_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUser): AppUser {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_AuditEntry_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntry): AuditEntry {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_CheckInMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInMethod): CheckInMethod {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CheckIn_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckIn): CheckIn {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ImportBatch_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportBatch): ImportBatch {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ImportStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportStatus): ImportStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResponse_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResponse): LoginResponse {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationType): RegistrationType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Registration_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Registration): Registration {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResult_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResult): SearchResult {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ShareholderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShareholderStatus): ShareholderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Shareholder_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shareholder): Shareholder {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckIn]): CheckIn | null {
    return value.length === 0 ? null : from_candid_CheckIn_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImportBatch]): ImportBatch | null {
    return value.length === 0 ? null : from_candid_ImportBatch_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registration]): Registration | null {
    return value.length === 0 ? null : from_candid_Registration_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shareholder]): Shareholder | null {
    return value.length === 0 ? null : from_candid_Shareholder_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ImportStatus;
    totalRows: bigint;
    duplicatesSkipped: bigint;
    filename: string;
    importedRows: bigint;
    uploadedAt: bigint;
    uploadedBy: string;
}): {
    id: string;
    status: ImportStatus;
    totalRows: bigint;
    duplicatesSkipped: bigint;
    filename: string;
    importedRows: bigint;
    uploadedAt: bigint;
    uploadedBy: string;
} {
    return {
        id: value.id,
        status: from_candid_ImportStatus_n14(_uploadFile, _downloadFile, value.status),
        totalRows: value.totalRows,
        duplicatesSkipped: value.duplicatesSkipped,
        filename: value.filename,
        importedRows: value.importedRows,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ShareholderStatus;
    tags: Array<string>;
    fullName: string;
    importedAt: bigint;
    importedBy: string;
    email: [] | [string];
    shareholderNumber: string;
    idNumber: string;
    phone: [] | [string];
    shareholding: bigint;
}): {
    id: string;
    status: ShareholderStatus;
    tags: Array<string>;
    fullName: string;
    importedAt: bigint;
    importedBy: string;
    email?: string;
    shareholderNumber: string;
    idNumber: string;
    phone?: string;
    shareholding: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ShareholderStatus_n19(_uploadFile, _downloadFile, value.status),
        tags: value.tags,
        fullName: value.fullName,
        importedAt: value.importedAt,
        importedBy: value.importedBy,
        email: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.email)),
        shareholderNumber: value.shareholderNumber,
        idNumber: value.idNumber,
        phone: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.phone)),
        shareholding: value.shareholding
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: string;
    username: string;
    createdAt: bigint;
    role: _UserRole;
    isActive: boolean;
    passwordHash: string;
    sessionExpiry: [] | [bigint];
    lastLogin: [] | [bigint];
    mustChangePassword: boolean;
}): {
    principal: string;
    username: string;
    createdAt: bigint;
    role: UserRole;
    isActive: boolean;
    passwordHash: string;
    sessionExpiry?: bigint;
    lastLogin?: bigint;
    mustChangePassword: boolean;
} {
    return {
        principal: value.principal,
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        passwordHash: value.passwordHash,
        sessionExpiry: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.sessionExpiry)),
        lastLogin: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.lastLogin)),
        mustChangePassword: value.mustChangePassword
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    expiresAt: bigint;
    username: string;
    role: _UserRole;
}): {
    token: string;
    expiresAt: bigint;
    username: string;
    role: UserRole;
} {
    return {
        token: value.token,
        expiresAt: value.expiresAt,
        username: value.username,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    shareholderId: string;
    verificationCode: string;
    proxyContact: [] | [string];
    proxyProofKey: [] | [string];
    updatedAt: bigint;
    updatedBy: [] | [string];
    proxyFraudFlags: Array<string>;
    notes: [] | [string];
    proxyName: [] | [string];
    proxyProofValidated: boolean;
    registrationType: _RegistrationType;
    registeredAt: bigint;
    registeredBy: string;
}): {
    id: string;
    shareholderId: string;
    verificationCode: string;
    proxyContact?: string;
    proxyProofKey?: string;
    updatedAt: bigint;
    updatedBy?: string;
    proxyFraudFlags: Array<string>;
    notes?: string;
    proxyName?: string;
    proxyProofValidated: boolean;
    registrationType: RegistrationType;
    registeredAt: bigint;
    registeredBy: string;
} {
    return {
        id: value.id,
        shareholderId: value.shareholderId,
        verificationCode: value.verificationCode,
        proxyContact: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.proxyContact)),
        proxyProofKey: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.proxyProofKey)),
        updatedAt: value.updatedAt,
        updatedBy: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.updatedBy)),
        proxyFraudFlags: value.proxyFraudFlags,
        notes: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.notes)),
        proxyName: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.proxyName)),
        proxyProofValidated: value.proxyProofValidated,
        registrationType: from_candid_RegistrationType_n39(_uploadFile, _downloadFile, value.registrationType),
        registeredAt: value.registeredAt,
        registeredBy: value.registeredBy
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    entityId: string;
    performedAt: bigint;
    performedBy: string;
    details: string;
    entityType: string;
    ipAddress: [] | [string];
}): {
    id: string;
    action: string;
    entityId: string;
    performedAt: bigint;
    performedBy: string;
    details: string;
    entityType: string;
    ipAddress?: string;
} {
    return {
        id: value.id,
        action: value.action,
        entityId: value.entityId,
        performedAt: value.performedAt,
        performedBy: value.performedBy,
        details: value.details,
        entityType: value.entityType,
        ipAddress: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.ipAddress))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    username: string;
    role: _UserRole;
    mustChangePassword: boolean;
}): {
    token: string;
    username: string;
    role: UserRole;
    mustChangePassword: boolean;
} {
    return {
        token: value.token,
        username: value.username,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        mustChangePassword: value.mustChangePassword
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    items: Array<_Shareholder>;
}): {
    total: bigint;
    page: bigint;
    items: Array<Shareholder>;
} {
    return {
        total: value.total,
        page: value.page,
        items: from_candid_vec_n41(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    shareholderId: string;
    method: _CheckInMethod;
    checkedInAt: bigint;
    checkedInBy: string;
    registrationId: string;
}): {
    id: string;
    shareholderId: string;
    method: CheckInMethod;
    checkedInAt: bigint;
    checkedInBy: string;
    registrationId: string;
} {
    return {
        id: value.id,
        shareholderId: value.shareholderId,
        method: from_candid_CheckInMethod_n10(_uploadFile, _downloadFile, value.method),
        checkedInAt: value.checkedInAt,
        checkedInBy: value.checkedInBy,
        registrationId: value.registrationId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ManualQuick: null;
} | {
    QRScan: null;
} | {
    Manual: null;
}): CheckInMethod {
    return "ManualQuick" in value ? CheckInMethod.ManualQuick : "QRScan" in value ? CheckInMethod.QRScan : "Manual" in value ? CheckInMethod.Manual : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Complete: null;
} | {
    Processing: null;
} | {
    Pending: null;
}): ImportStatus {
    return "Failed" in value ? ImportStatus.Failed : "Complete" in value ? ImportStatus.Complete : "Processing" in value ? ImportStatus.Processing : "Pending" in value ? ImportStatus.Pending : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Shareholder;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Shareholder;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Shareholder_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    RegisteredProxy: null;
} | {
    RegisteredInPerson: null;
} | {
    NotRegistered: null;
} | {
    CheckedIn: null;
}): ShareholderStatus {
    return "RegisteredProxy" in value ? ShareholderStatus.RegisteredProxy : "RegisteredInPerson" in value ? ShareholderStatus.RegisteredInPerson : "NotRegistered" in value ? ShareholderStatus.NotRegistered : "CheckedIn" in value ? ShareholderStatus.CheckedIn : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AppUser;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AppUser;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AppUser_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewer: null;
} | {
    RegistrationOfficer: null;
} | {
    SuperAdmin: null;
}): UserRole {
    return "Viewer" in value ? UserRole.Viewer : "RegistrationOfficer" in value ? UserRole.RegistrationOfficer : "SuperAdmin" in value ? UserRole.SuperAdmin : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Session>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Session>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Proxy: null;
} | {
    InPerson: null;
}): RegistrationType {
    return "Proxy" in value ? RegistrationType.Proxy : "InPerson" in value ? RegistrationType.InPerson : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AppUser>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AppUser>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LoginResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LoginResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LoginResponse_n54(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Registration;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Registration;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Registration_n37(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ImportBatch;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ImportBatch;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ImportBatch_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CheckIn;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CheckIn;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CheckIn_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AGMSettings;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AGMSettings;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Session;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Session_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckIn>): Array<CheckIn> {
    return value.map((x)=>from_candid_CheckIn_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Registration>): Array<Registration> {
    return value.map((x)=>from_candid_Registration_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shareholder>): Array<Shareholder> {
    return value.map((x)=>from_candid_Shareholder_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEntry>): Array<AuditEntry> {
    return value.map((x)=>from_candid_AuditEntry_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImportBatch>): Array<ImportBatch> {
    return value.map((x)=>from_candid_ImportBatch_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppUser>): Array<AppUser> {
    return value.map((x)=>from_candid_AppUser_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CheckInMethod_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInMethod): _CheckInMethod {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ImportStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportStatus): _ImportStatus {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_ProxyData_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProxyData): _ProxyData {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationType): _RegistrationType {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationUpdate_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationUpdate): _RegistrationUpdate {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_ShareholderInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShareholderInput): _ShareholderInput {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_ShareholderStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShareholderStatus): _ShareholderStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProxyData | null): [] | [_ProxyData] {
    return value === null ? candid_none() : candid_some(to_candid_ProxyData_n59(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShareholderStatus | null): [] | [_ShareholderStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ShareholderStatus_n63(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tags: Array<string>;
    fullName: string;
    email?: string;
    shareholderNumber: string;
    idNumber: string;
    phone?: string;
    shareholding: bigint;
}): {
    tags: Array<string>;
    fullName: string;
    email: [] | [string];
    shareholderNumber: string;
    idNumber: string;
    phone: [] | [string];
    shareholding: bigint;
} {
    return {
        tags: value.tags,
        fullName: value.fullName,
        email: value.email ? candid_some(value.email) : candid_none(),
        shareholderNumber: value.shareholderNumber,
        idNumber: value.idNumber,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        shareholding: value.shareholding
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proxyContact: string;
    proxyProofKey?: string;
    proxyName: string;
}): {
    proxyContact: string;
    proxyProofKey: [] | [string];
    proxyName: string;
} {
    return {
        proxyContact: value.proxyContact,
        proxyProofKey: value.proxyProofKey ? candid_some(value.proxyProofKey) : candid_none(),
        proxyName: value.proxyName
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proxyData?: ProxyData;
    notes?: string;
}): {
    proxyData: [] | [_ProxyData];
    notes: [] | [string];
} {
    return {
        proxyData: value.proxyData ? candid_some(to_candid_ProxyData_n59(_uploadFile, _downloadFile, value.proxyData)) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Viewer: null;
} | {
    RegistrationOfficer: null;
} | {
    SuperAdmin: null;
} {
    return value == UserRole.Viewer ? {
        Viewer: null
    } : value == UserRole.RegistrationOfficer ? {
        RegistrationOfficer: null
    } : value == UserRole.SuperAdmin ? {
        SuperAdmin: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationType): {
    Proxy: null;
} | {
    InPerson: null;
} {
    return value == RegistrationType.Proxy ? {
        Proxy: null
    } : value == RegistrationType.InPerson ? {
        InPerson: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInMethod): {
    ManualQuick: null;
} | {
    QRScan: null;
} | {
    Manual: null;
} {
    return value == CheckInMethod.ManualQuick ? {
        ManualQuick: null
    } : value == CheckInMethod.QRScan ? {
        QRScan: null
    } : value == CheckInMethod.Manual ? {
        Manual: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShareholderStatus): {
    RegisteredProxy: null;
} | {
    RegisteredInPerson: null;
} | {
    NotRegistered: null;
} | {
    CheckedIn: null;
} {
    return value == ShareholderStatus.RegisteredProxy ? {
        RegisteredProxy: null
    } : value == ShareholderStatus.RegisteredInPerson ? {
        RegisteredInPerson: null
    } : value == ShareholderStatus.NotRegistered ? {
        NotRegistered: null
    } : value == ShareholderStatus.CheckedIn ? {
        CheckedIn: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportStatus): {
    Failed: null;
} | {
    Complete: null;
} | {
    Processing: null;
} | {
    Pending: null;
} {
    return value == ImportStatus.Failed ? {
        Failed: null
    } : value == ImportStatus.Complete ? {
        Complete: null
    } : value == ImportStatus.Processing ? {
        Processing: null
    } : value == ImportStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ShareholderInput>): Array<_ShareholderInput> {
    return value.map((x)=>to_candid_ShareholderInput_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
